#!/bin/bash
#
# CLIProxyAPI Dashboard installation script
# Installs Docker, writes infrastructure/.env, installs a systemd unit,
# and optionally configures backups, UFW, and the deploy webhook.
#

set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

check_port_conflict() {
    local port=$1

    if command -v ss &> /dev/null; then
        ss -tln 2>/dev/null | grep -q ":$port " && return 0
    elif command -v lsof &> /dev/null; then
        lsof -i ":$port" 2>/dev/null | grep -q LISTEN && return 0
    elif command -v netstat &> /dev/null; then
        netstat -tln 2>/dev/null | grep -q ":$port " && return 0
    fi

    return 1
}

check_container_conflicts() {
    local container_names=("cliproxyapi" "cliproxyapi-dashboard" "cliproxyapi-docker-proxy" "cliproxyapi-postgres")
    local conflicts=()

    if ! command -v docker &> /dev/null; then
        return 0
    fi

    if ! docker ps &> /dev/null 2>&1; then
        return 0
    fi

    for container in "${container_names[@]}"; do
        if docker ps -a --format '{{.Names}}' 2>/dev/null | grep -q "^${container}$"; then
            conflicts+=("$container")
        fi
    done

    if [ ${#conflicts[@]} -gt 0 ]; then
        printf '%s\n' "${conflicts[@]}"
    fi
}

install_docker() {
    if command -v docker &> /dev/null && docker compose version &> /dev/null; then
        log_success "Docker and Docker Compose already installed"
        return
    fi

    log_info "Installing Docker Engine and Docker Compose plugin..."

    apt-get update
    apt-get install -y ca-certificates curl gnupg lsb-release

    install -m 0755 -d /etc/apt/keyrings

    if [ ! -f /etc/apt/keyrings/docker.gpg ]; then
        curl -fsSL "$DOCKER_REPO_URL/gpg" | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
        chmod a+r /etc/apt/keyrings/docker.gpg
    fi

    echo \
      "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] $DOCKER_REPO_URL $DISTRO_CODENAME stable" \
      > /etc/apt/sources.list.d/docker.list

    apt-get update
    apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

    systemctl enable docker
    systemctl start docker

    log_success "Docker installed"
}

ensure_docker_running() {
    if ! systemctl is-active --quiet docker; then
        log_info "Starting Docker..."
        systemctl start docker
    fi

    if ! docker info > /dev/null 2>&1; then
        log_error "Docker daemon is not available"
        exit 1
    fi
}

configure_ufw() {
    if [[ ! "$CONFIGURE_UFW" =~ ^[Yy]$ ]]; then
        log_info "Skipping UFW configuration"
        return
    fi

    log_info "Configuring UFW..."

    if ! command -v ufw &> /dev/null; then
        apt-get update
        apt-get install -y ufw
    fi

    if ! ufw status | grep -q "22/tcp"; then
        ufw limit 22/tcp comment 'SSH'
    fi

    if [ "$OAUTH_ENABLED" -eq 1 ]; then
        for port in 8085 1455 54545 51121 11451; do
            if ! ufw status | grep -q "${port}/tcp"; then
                ufw allow "${port}/tcp" comment "CLIProxyAPI OAuth callback"
            fi
        done
    fi

    if ! ufw status | grep -q "Status: active"; then
        ufw --force enable
    fi

    log_success "UFW configured"
}

create_env_file() {
    local env_file="$INSTALL_DIR/infrastructure/.env"
    local skip_env=0

    if [ -f "$env_file" ]; then
        log_warning ".env file already exists"
        read -p "Overwrite .env file? [y/N]: " OVERWRITE_ENV
        if [[ ! "$OVERWRITE_ENV" =~ ^[Yy]$ ]]; then
            skip_env=1
        fi
    fi

    if [ "$skip_env" -eq 1 ]; then
        log_info "Keeping existing .env file"
        set -a
        source "$env_file"
        set +a
        return
    fi

    cat > "$env_file" << EOF
# CLIProxyAPI Dashboard stack
# Generated by install.sh on $(date)

DATABASE_URL=postgresql://cliproxyapi:${POSTGRES_PASSWORD}@postgres:5432/cliproxyapi
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

JWT_SECRET=${JWT_SECRET}
MANAGEMENT_API_KEY=${MANAGEMENT_API_KEY}
COLLECTOR_API_KEY=${COLLECTOR_API_KEY}
PROVIDER_ENCRYPTION_KEY=${PROVIDER_ENCRYPTION_KEY}

CLIPROXYAPI_MANAGEMENT_URL=http://cliproxyapi:8317/v0/management

INSTALL_DIR=${INSTALL_DIR}
TZ=UTC
LOG_LEVEL=info

DASHBOARD_URL=${DASHBOARD_URL}
API_URL=${API_URL}
EOF

    chmod 600 "$env_file"
    log_success ".env file created at $env_file"
}

install_systemd_service() {
    local service_file="/etc/systemd/system/cliproxyapi-stack.service"
    local manage_script="$INSTALL_DIR/infrastructure/manage.sh"
    local skip_service=0

    if [ -f "$service_file" ]; then
        log_warning "Systemd service already exists"
        read -p "Overwrite service file? [y/N]: " OVERWRITE_SERVICE
        if [[ ! "$OVERWRITE_SERVICE" =~ ^[Yy]$ ]]; then
            skip_service=1
        fi
    fi

    if [ "$skip_service" -eq 1 ]; then
        log_info "Keeping existing service file"
        return
    fi

    chmod +x "$manage_script"

    cat > "$service_file" << EOF
[Unit]
Description=CLIProxyAPI Dashboard Stack (Docker Compose)
Requires=docker.service
After=docker.service network-online.target
Wants=network-online.target

[Service]
Type=oneshot
RemainAfterExit=true
WorkingDirectory=${INSTALL_DIR}/infrastructure
ExecStart=${manage_script} up
ExecStop=${manage_script} down
TimeoutStartSec=300
TimeoutStopSec=120
Restart=on-failure
RestartSec=10s
User=root
Group=root

[Install]
WantedBy=multi-user.target
EOF

    systemctl daemon-reload
    systemctl enable cliproxyapi-stack.service

    log_success "Systemd service installed"
}

setup_backup_scripts() {
    local scripts_dir="$INSTALL_DIR/scripts"

    if [ ! -d "$scripts_dir" ] || [ ! -f "$scripts_dir/backup.sh" ]; then
        log_error "scripts/ directory is missing"
        exit 1
    fi

    chmod +x "$scripts_dir/backup.sh"
    chmod +x "$scripts_dir/restore.sh"
    chmod +x "$scripts_dir/rotate-backups.sh"

    log_success "Backup scripts are ready"

    if [ "$BACKUP_INTERVAL" = "none" ]; then
        return
    fi

    local cron_schedule
    local cron_comment

    if [ "$BACKUP_INTERVAL" = "daily" ]; then
        cron_schedule="0 2 * * *"
        cron_comment="CLIProxyAPI daily backup"
    else
        cron_schedule="0 2 * * 0"
        cron_comment="CLIProxyAPI weekly backup"
    fi

    if crontab -l 2>/dev/null | grep -q "$scripts_dir/backup.sh"; then
        log_warning "Backup cron job already exists"
        return
    fi

    (
        crontab -l 2>/dev/null || true
        echo "# $cron_comment"
        echo "$cron_schedule $scripts_dir/backup.sh >> $INSTALL_DIR/backups/backup.log 2>&1 && $scripts_dir/rotate-backups.sh $BACKUP_RETENTION >> $INSTALL_DIR/backups/backup.log 2>&1"
    ) | crontab -

    log_success "Backup cron job installed"
}

setup_usage_collector() {
    local collector_url="http://127.0.0.1:3000"
    local cron_schedule="*/5 * * * *"
    local cron_cmd="curl -sf -X POST ${collector_url}/api/usage/collect -H 'Authorization: Bearer ${COLLECTOR_API_KEY}' -o /dev/null"

    if crontab -l 2>/dev/null | grep -q "/api/usage/collect"; then
        log_warning "Usage collector cron job already exists"
        return
    fi

    (
        crontab -l 2>/dev/null || true
        echo "# CLIProxyAPI usage collector (every 5 minutes)"
        echo "$cron_schedule $cron_cmd"
    ) | crontab -

    log_success "Usage collector cron job installed"
}

install_webhook_service() {
    read -p "Install webhook deploy service? [y/N]: " INSTALL_WEBHOOK
    if [[ ! "$INSTALL_WEBHOOK" =~ ^[Yy]$ ]]; then
        log_info "Skipping webhook installation"
        return
    fi

    if ! command -v webhook &> /dev/null; then
        apt-get update
        apt-get install -y webhook
    fi

    local deploy_secret
    deploy_secret="$(openssl rand -hex 32)"

    mkdir -p /etc/webhook
    sed \
        -e "s|{{DEPLOY_SECRET}}|${deploy_secret}|g" \
        -e "s|{{INSTALL_DIR}}|${INSTALL_DIR}|g" \
        -e "s|{{LOG_DIR}}|/var/log/cliproxyapi|g" \
        "$INSTALL_DIR/infrastructure/webhook.yaml" > /etc/webhook/hooks.yaml
    chmod 600 /etc/webhook/hooks.yaml
    chmod +x "$INSTALL_DIR/infrastructure/deploy.sh"
    chmod +x "$INSTALL_DIR/infrastructure/manage.sh"

    cat > /etc/systemd/system/webhook-deploy.service << EOF
[Unit]
Description=Webhook Deploy Service for CLIProxyAPI Dashboard
After=network.target

[Service]
Type=simple
ExecStart=/usr/bin/webhook -hooks /etc/webhook/hooks.yaml -port 9000 -verbose
Restart=on-failure
RestartSec=5
User=root
Group=root

[Install]
WantedBy=multi-user.target
EOF

    systemctl daemon-reload
    systemctl enable webhook-deploy.service
    systemctl start webhook-deploy.service

    if ! grep -q "^WEBHOOK_HOST=" "$INSTALL_DIR/infrastructure/.env"; then
        cat >> "$INSTALL_DIR/infrastructure/.env" << EOF

WEBHOOK_HOST=http://host.docker.internal:9000
DEPLOY_SECRET=${deploy_secret}
EOF
    fi

    local override_file="$INSTALL_DIR/infrastructure/docker-compose.override.yml"
    if [ ! -f "$override_file" ]; then
        cat > "$override_file" << 'EOF'
services:
  dashboard:
    extra_hosts:
      - "host.docker.internal:host-gateway"
EOF
    elif ! grep -q "host.docker.internal:host-gateway" "$override_file"; then
        log_warning "Please add host.docker.internal mapping to $override_file manually"
    fi

    log_success "Webhook deploy service installed"
}

if [ "$EUID" -ne 0 ]; then
    log_error "This script must be run as root"
    exit 1
fi

INSTALL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
log_info "Installation directory: $INSTALL_DIR"

if ! command -v apt-get &> /dev/null; then
    log_error "This script only supports Ubuntu/Debian systems"
    exit 1
fi

if [ -f /etc/os-release ]; then
    . /etc/os-release
    DISTRO_ID="${ID:-}"
    DISTRO_CODENAME="${VERSION_CODENAME:-}"
else
    log_error "Cannot detect Linux distribution"
    exit 1
fi

case "$DISTRO_ID" in
    ubuntu)
        DOCKER_REPO_URL="https://download.docker.com/linux/ubuntu"
        ;;
    debian)
        DOCKER_REPO_URL="https://download.docker.com/linux/debian"
        ;;
    *)
        log_error "Unsupported distribution: $DISTRO_ID"
        exit 1
        ;;
esac

if [ -z "$DISTRO_CODENAME" ]; then
    log_error "Cannot determine distro codename"
    exit 1
fi

log_info "Detected distribution: $DISTRO_ID ($DISTRO_CODENAME)"
echo ""

log_info "=== Configuration ==="
echo ""

read -p "Public dashboard URL [default: http://localhost:3000]: " DASHBOARD_URL
DASHBOARD_URL="${DASHBOARD_URL:-http://localhost:3000}"

read -p "Public API URL [default: http://localhost:8317]: " API_URL
API_URL="${API_URL:-http://localhost:8317}"

read -p "Enable OAuth callback ports in the firewall? [y/N]: " OAUTH_ENABLED_INPUT
if [[ "$OAUTH_ENABLED_INPUT" =~ ^[Yy]$ ]]; then
    OAUTH_ENABLED=1
else
    OAUTH_ENABLED=0
fi

read -p "Configure UFW firewall now? [y/N]: " CONFIGURE_UFW

echo ""
log_info "Select backup interval:"
echo "  1) Daily backups (keep last 7)"
echo "  2) Weekly backups (keep last 4)"
echo "  3) No automated backups"
while true; do
    read -p "Enter choice [1-3]: " BACKUP_CHOICE
    case "$BACKUP_CHOICE" in
        1)
            BACKUP_INTERVAL="daily"
            BACKUP_RETENTION=7
            break
            ;;
        2)
            BACKUP_INTERVAL="weekly"
            BACKUP_RETENTION=4
            break
            ;;
        3)
            BACKUP_INTERVAL="none"
            BACKUP_RETENTION=0
            break
            ;;
        *)
            log_error "Invalid choice"
            ;;
    esac
done

echo ""
log_info "Configuration summary:"
log_info "  Dashboard URL: $DASHBOARD_URL"
log_info "  API URL: $API_URL"
log_info "  OAuth callback ports: $([ "$OAUTH_ENABLED" -eq 1 ] && echo 'open' || echo 'closed')"
log_info "  UFW configuration: $([[ "$CONFIGURE_UFW" =~ ^[Yy]$ ]] && echo 'enabled' || echo 'skipped')"
log_info "  Backup interval: $BACKUP_INTERVAL"
echo ""

read -p "Continue with installation? [y/N]: " CONFIRM
if [[ ! "$CONFIRM" =~ ^[Yy]$ ]]; then
    log_warning "Installation cancelled"
    exit 0
fi

echo ""
log_info "=== Preflight Checks ==="
echo ""

REQUIRED_PORTS=(3000 8317)
if [ "$OAUTH_ENABLED" -eq 1 ]; then
    REQUIRED_PORTS+=(8085 1455 54545 51121 11451)
fi

PORT_CONFLICTS=()
for port in "${REQUIRED_PORTS[@]}"; do
    if check_port_conflict "$port"; then
        PORT_CONFLICTS+=("$port")
    fi
done

if [ ${#PORT_CONFLICTS[@]} -gt 0 ]; then
    log_error "Port conflicts detected: ${PORT_CONFLICTS[*]}"
    exit 1
fi

CONTAINER_CONFLICTS=$(check_container_conflicts || true)
if [ -n "$CONTAINER_CONFLICTS" ]; then
    log_warning "Existing Docker containers found:"
    echo "$CONTAINER_CONFLICTS"
    read -p "Continue anyway? [y/N]: " CONTINUE_CONFLICTS
    if [[ ! "$CONTINUE_CONFLICTS" =~ ^[Yy]$ ]]; then
        exit 1
    fi
fi

echo ""
log_info "=== Docker Installation ==="
echo ""

install_docker
ensure_docker_running

echo ""
log_info "=== Secret Generation ==="
echo ""

JWT_SECRET="$(openssl rand -base64 32)"
MANAGEMENT_API_KEY="$(openssl rand -hex 32)"
POSTGRES_PASSWORD="$(openssl rand -hex 32)"
COLLECTOR_API_KEY="$(openssl rand -hex 32)"
PROVIDER_ENCRYPTION_KEY="$(openssl rand -hex 32)"

log_success "Secrets generated"

echo ""
log_info "=== Firewall Configuration ==="
echo ""

configure_ufw

echo ""
log_info "=== Environment Configuration ==="
echo ""

create_env_file

echo ""
log_info "=== Systemd Service Installation ==="
echo ""

install_systemd_service

echo ""
log_info "=== Backup Setup ==="
echo ""

setup_backup_scripts

echo ""
log_info "=== Usage Collector ==="
echo ""

setup_usage_collector

echo ""
log_info "=== Optional Webhook ==="
echo ""

install_webhook_service

echo ""
log_info "=== Installation Complete ==="
echo ""
log_success "CLIProxyAPI Dashboard stack installation completed successfully"
echo ""
echo "Next steps:"
echo "  1. Start the stack:"
echo "     sudo systemctl start cliproxyapi-stack"
echo ""
echo "  2. Check status:"
echo "     sudo systemctl status cliproxyapi-stack"
echo ""
echo "  3. View logs:"
echo "     cd $INSTALL_DIR/infrastructure"
echo "     docker compose logs -f"
echo ""
echo "  4. Local service endpoints:"
echo "     Dashboard: http://127.0.0.1:3000"
echo "     API: http://127.0.0.1:8317"
echo ""
echo "  5. Public URLs configured in the dashboard:"
echo "     Dashboard: $DASHBOARD_URL"
echo "     API: $API_URL"
echo ""
echo "  6. Create the first admin account in the dashboard, then configure"
echo "     providers, proxy settings, and API keys."
echo ""
echo "If you need public HTTPS access, place your own reverse proxy in front of"
echo "127.0.0.1:3000 and 127.0.0.1:8317."
echo ""
log_warning "Secrets are stored in $INSTALL_DIR/infrastructure/.env"
